# Generated by Django 4.0.3 on 2022-03-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_meme_comment_meme_like_meme_reach_meme_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='engagement',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='meme',
            name='name',
            field=models.CharField(default='mymeme', max_length=50),
        ),
    ]
