# Generated by Django 4.0.3 on 2022-03-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_meme_engagement_meme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='engagement',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
