# Generated by Django 4.0.3 on 2022-03-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_meme_engagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='engagement',
        ),
    ]
